name: build

on:
  repository_dispatch:
    types: [build-on-demand]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Go build
        uses: izumin5210/action-go-crossbuild@v1.0.0
        with:
          arch: 386
          ldflags: "-s -w"
          os: windows
      - name: Setup MinGW
        id: mingw
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86
      - name: C++ build
        env:
          gxx: ${{ steps.mingw.outputs.gxx }}
        run: |
          sudo apt install upx
          cd runnerc
          ${gxx} main.cpp -I include lib/cube_api.lib -s -m32 -o runner
          mv runner.exe ../dist
          upx -9 -vf --lzma --compress-icons=0 *.exe
          cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cubeidler
          path: |
            ~/dist
            !~/dist/cube_api64.dll
