name: build

on:
  repository_dispatch:
    types: [build-on-demand]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21.0'
      - name: Go build
        run: |
          sudo apt install upx
          set GOARCH=x86_64
          set GOOS=windows
          cd runner
          go build -ldflags="-s -w"
          mv runner.exe ../dist/
          cd ..
          go build -ldflags="-s -w"
          mv cubeidler.exe ../dist/
          cd dist
          upx -9 -vf --lzma --compress-icons=0 *.exe
          cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cubeidler
          path: |
            ~/dist
            !~/dist/cube_api.dll
