name: build

on:
  repository_dispatch:
    types: [build-on-demand]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21.0'
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86
      - name: Setup UPX
        uses: crazy-max/ghaction-upx@v2.3.0
        with:
          install-only: true
      - name: Build
        run: |
          cd runnerc
          i686-w64-mingw32-g++ main.cpp -I include lib/cube_api.lib -s -m32 -o runner
          mv runner.exe ../dist/
          cd ..
          set GOARCH=386
          set GOOS=windows
          go build -ldflags="-s -w"
          mv cubeidler.exe ./dist/
          cd dist
          upx --brute *.exe
          cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cubeidler
          path: |
            ./dist
            !./dist/cube_api64.dll
