name: build

on:
  repository_dispatch:
    types: [build-on-demand]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: '1.21.0'
      - name: Set up MinGW\
        id: mingw
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86
      - name: Setup UPX
        uses: crazy-max/ghaction-upx@v2.3.0
        with:
          install-only: true
      - name: Build
        env:
          gxx: ${{ steps.mingw.outputs.gxx }}
        run: |
          cd runnerc
          %gxx% main.cpp -I include lib/cube_api.lib -s -m32 -o runner
          mv runner.exe ../dist/
          cd ..
          set GOARCH=386
          set GOOS=windows
          go build -ldflags="-s -w"
          mv cubeidler.exe ../dist/
          cd dist
          upx -9 -vf --lzma --compress-icons=0 *.exe
          cd ..
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cubeidler
          path: |
            ~/dist
            !~/dist/cube_api.dll
